require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe BooksController, type: :controller do
  # include ApiDoc::V1::Books

  let(:valid_attributes) {
    attributes_for(:book)
  }

  let(:invalid_attributes) {
     { name: '' }
  }

  let(:author) { create(:author) }
  let!(:book) { create(:book, author: author) }

  describe "GET #index" do
    it "returns 200 status" do
      get :index
      expect(response).to have_http_status(:ok)
    end
  end

  describe "GET #show" do
    it "returns 200 status" do
      get :show, params: {id: book.id}
      expect(response).to have_http_status(:ok)
    end
  end

  describe "GET #new" do
    it "returns 200 status" do
      get :new
      expect(response).to have_http_status(:ok)
    end
  end

  describe "GET #edit" do
    it "assigns the requested book as @book" do
      get :edit, params: {id: book.id}
      expect(response).to have_http_status(:ok)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Book" do
        expect {
          post :create, params: {book: valid_attributes}
        }.to change(Book, :count).by(1)
      end

      it "returns 201 status" do
        post :create, params: {book: valid_attributes}
        expect(response).to have_http_status(201)
      end
    end

    context "with invalid params" do
      it "returns 422 status" do
        post :create, params: {book: invalid_attributes}
        expect(response).to have_http_status(422)
      end

      it "doesn't create a new book" do
        expect {
          post :create, params: {book: invalid_attributes}
        }.to_not change(Book.count)
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested book" do
        put :update, params: {id: book.id, book: {name: 'New Book'}}
        expect(book.reload).name to eq 'New Book'
      end

      it "returns 200 status" do
        put :update, params: {id: book.id, book: valid_attributes}
        expect(response).to have_http_status(:ok)
      end
    end

    context "with invalid params" do
      it "returns 422 status" do
        put :update, params: {id: book.id, book: invalid_attributes}, session: valid_session
        expect(response).to have_http_status(422)
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested book" do
      expect {
        delete :destroy, params: {id: book.id}
      }.to change(Book, :count).by(-1)
    end

    it "returns 204 status" do
      delete :destroy, params: {id: book.id}
      expect(response).to have_http_status(204)
    end
  end

end
